"""Remove doc_id from raptor_trees - tree belongs to KB not document

Revision ID: 138d3b99c998
Revises: 1f95ae023e6c
Create Date: 2025-08-25 10:34:31.722657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138d3b99c998'
down_revision = '1f95ae023e6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('raptor_trees_doc_id_fkey'), 'raptor_trees', type_='foreignkey')
    op.drop_column('raptor_trees', 'doc_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raptor_trees', sa.Column('doc_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('raptor_trees_doc_id_fkey'), 'raptor_trees', 'documents', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    # ### end Alembic commands ###

