"""Set default value for total_tokens in knowledge_bases

Revision ID: 1f95ae023e6c
Revises: 772871abe90a
Create Date: 2025-08-25 04:58:38.213455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f95ae023e6c'
down_revision = '772871abe90a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, set default value for existing NULL records
    op.execute("UPDATE knowledge_bases SET total_tokens = 0 WHERE total_tokens IS NULL")
    
    # Then alter column to NOT NULL with default
    op.alter_column('knowledge_bases', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_bases', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               server_default=None)
    # ### end Alembic commands ###
