"""add_processing_stats_to_documents

Revision ID: 2625be4c2016
Revises: 138d3b99c998
Create Date: 2025-08-26 08:26:53.400931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2625be4c2016'
down_revision = '138d3b99c998'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chunks_doc_index'), 'chunks', type_='unique')
    op.create_index('ix_chunks_doc_chunk_unique', 'chunks', ['doc_id', 'chunk_index'], unique=True)
    op.create_index(op.f('ix_chunks_doc_id'), 'chunks', ['doc_id'], unique=False)
    op.create_index('ix_documents_tenant_kb', 'documents', ['tenant_id', 'kb_id'], unique=False)
    op.create_index('ix_documents_tenant_kb_checksum', 'documents', ['tenant_id', 'kb_id', 'checksum'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tenant_kb_checksum', table_name='documents')
    op.drop_index('ix_documents_tenant_kb', table_name='documents')
    op.drop_index(op.f('ix_chunks_doc_id'), table_name='chunks')
    op.drop_index('ix_chunks_doc_chunk_unique', table_name='chunks')
    op.create_unique_constraint(op.f('uq_chunks_doc_index'), 'chunks', ['doc_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###



