"""remove_unnecessary_fields_keep_simple_schema

Revision ID: 2b2033901f4b
Revises: 89966aa1aa09
Create Date: 2025-08-26 10:19:35.977721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2033901f4b'
down_revision = '89966aa1aa09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove unnecessary fields from documents table
    op.drop_index('ix_documents_source', table_name='documents')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'extra_meta')
    
    # Remove unnecessary fields from chunks table
    op.drop_index('ix_chunks_hash', table_name='chunks')
    op.drop_column('chunks', 'hash')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the removed fields (for rollback)
    op.add_column('chunks', sa.Column('hash', sa.String(), nullable=True))
    op.create_index('ix_chunks_hash', 'chunks', ['hash'], unique=False)
    
    op.add_column('documents', sa.Column('extra_meta', sa.dialects.postgresql.JSONB(), nullable=True))
    op.add_column('documents', sa.Column('tags', sa.dialects.postgresql.JSONB(), nullable=True))
    op.add_column('documents', sa.Column('source', sa.String(), nullable=True))
    op.create_index('ix_documents_source', 'documents', ['source'], unique=False)
    
    # ### end Alembic commands ###



