"""enhance_schema_with_relationships_and_mapping

Revision ID: 89966aa1aa09
Revises: 2625be4c2016
Create Date: 2025-08-26 09:56:10.081323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89966aa1aa09'
down_revision = '2625be4c2016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raptor_tree_node_chunks',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['raptor_tree_nodes.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'chunk_id')
    )
    op.create_index('ix_tree_node_chunks_chunk', 'raptor_tree_node_chunks', ['chunk_id'], unique=False)
    op.create_index('ix_tree_node_chunks_node', 'raptor_tree_node_chunks', ['node_id'], unique=False)
    op.create_index('ix_tree_node_chunks_rank', 'raptor_tree_node_chunks', ['node_id', 'rank'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'knowledge_bases', ['kb_id'], ['kb_id'], ondelete='CASCADE')
    op.add_column('chunks', sa.Column('hash', sa.String(), nullable=True))
    op.create_index('ix_chunks_hash', 'chunks', ['hash'], unique=False)
    op.add_column('documents', sa.Column('source', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('extra_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_documents_source', 'documents', ['source'], unique=False)
    op.create_foreign_key(None, 'documents', 'knowledge_bases', ['kb_id'], ['kb_id'], ondelete='CASCADE')
    op.add_column('raptor_trees', sa.Column('doc_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_raptor_trees_doc_id'), 'raptor_trees', ['doc_id'], unique=False)
    op.create_foreign_key(None, 'raptor_trees', 'documents', ['doc_id'], ['doc_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'raptor_trees', 'knowledge_bases', ['kb_id'], ['kb_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raptor_trees', type_='foreignkey')
    op.drop_constraint(None, 'raptor_trees', type_='foreignkey')
    op.drop_index(op.f('ix_raptor_trees_doc_id'), table_name='raptor_trees')
    op.drop_column('raptor_trees', 'doc_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index('ix_documents_source', table_name='documents')
    op.drop_column('documents', 'extra_meta')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'source')
    op.drop_index('ix_chunks_hash', table_name='chunks')
    op.drop_column('chunks', 'hash')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index('ix_tree_node_chunks_rank', table_name='raptor_tree_node_chunks')
    op.drop_index('ix_tree_node_chunks_node', table_name='raptor_tree_node_chunks')
    op.drop_index('ix_tree_node_chunks_chunk', table_name='raptor_tree_node_chunks')
    op.drop_table('raptor_tree_node_chunks')
    # ### end Alembic commands ###



