"""Fix assistant cascade delete: change chat_sessions.assistant_id FK to CASCADE

Revision ID: 93501c24e63a
Revises: 40291f505078
Create Date: 2025-09-03 09:42:16.880149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93501c24e63a'
down_revision = '40291f505078'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_sessions_assistant_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'assistants', ['assistant_id'], ['assistant_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_assistant_id_fkey'), 'chat_sessions', 'assistants', ['assistant_id'], ['assistant_id'], ondelete='SET NULL')
    # ### end Alembic commands ###



