"""Add assistants table

Revision ID: b960ccddb7be
Revises: 2d2637883dd7
Create Date: 2025-09-03 08:21:26.956087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b960ccddb7be'
down_revision = '2d2637883dd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('assistant_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('kb_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.kb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assistant_id')
    )
    op.create_index(op.f('ix_assistants_kb_id'), 'assistants', ['kb_id'], unique=False)
    op.create_index('ix_assistants_tenant_id', 'assistants', ['tenant_id'], unique=False)
    op.create_index('ix_assistants_tenant_kb', 'assistants', ['tenant_id', 'kb_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('assistant_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_assistant_id'), 'chat_sessions', ['assistant_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'assistants', ['assistant_id'], ['assistant_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_assistant_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'assistant_id')
    op.drop_index('ix_assistants_tenant_kb', table_name='assistants')
    op.drop_index('ix_assistants_tenant_id', table_name='assistants')
    op.drop_index(op.f('ix_assistants_kb_id'), table_name='assistants')
    op.drop_table('assistants')
    # ### end Alembic commands ###



