"""remove_unused_document_content_column

Revision ID: c7a4b728ec0f
Revises: eccec4f6cc32
Create Date: 2025-09-02 18:25:52.913508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a4b728ec0f'
down_revision = 'eccec4f6cc32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###



