"""Add summary and root to embedding_owner_type enum

Revision ID: eccec4f6cc32
Revises: 26a522d86cb7
Create Date: 2025-08-31 23:02:43.310656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccec4f6cc32'
down_revision = '26a522d86cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



